name: build-develop

on:
  push:
    branches:
      - develop

jobs:
  build-develop:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-source
        uses: actions/checkout@v4
        with:
          ref: develop
          path: repo
      - id: configure-environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: guides
          channels: conda-forge
          environment-file: repo/environment.yml
          miniforge-version: latest
          use-mamba: true
      - id: get-baseurl
        run: |
          url=$(gh api "repos/${{ github.repository }}" --jq ".html_url")
          echo "BASEURL=${url}" >> "$GITHUB_OUTPUT"
        shell: bash
      - id: build-html
        run: sphinx-build repo/source build/dev
        shell: bash
        env:
          BASEURL: ${{ steps.get-baseurl.outputs.BASEURL }}
      - id: deploy-changes
        run: |
          cd repo
          git pull --all
          git config user.name "$(git show -s --format='%an' HEAD)"
          git config user.email "$(git show -s --format='%ae' HEAD)"
          git checkout gh-pages -- || git switch --orphan gh-pages
          rsync -a ../build/ ./
          git add -A
          git commit -m "$MESSAGE"
          git push -u origin gh-pages
        shell: bash
        env:
          MESSAGE: ${{ github.sha }}
